services:
  neo4j:
    image: neo4j:community
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - $PWD/neo4j/data:/data
      - $PWD/neo4j/import:/import
    environment:
      - NEO4J_AUTH=neo4j/pleaseletmein
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_db_tx__log_rotation_retention__policy=false
      - NEO4J_server_directories_import=/import
    healthcheck:
        test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
        interval: 5s
        timeout: 3s
        retries: 5
    networks:
      - net
networks:
  net: